#!/usr/bin/env bash

cp ./flash ~/.config/
cp ./cheat_sheet ~/.config/
cp ./volume_ctrl ~/.config/
cp -r ./nvim/ ~/.config/
cp -r ./tmux/tmux.conf ~/.config/
cp ./.zshrc ../
cp -r ./i3/ ~/.config/
cp -r ./i3status/ ~/.config/
cp -r ./Xresources ~/.config/
